### PR TITLE
fix: re-enable preview for interactive objkts

### PR DESCRIPTION
**Pull request by Zir0h**
Fixes regression from https://github.com/teia-community/teia-ui/pull/346
Don't know if this is the right way of doing it though :sweat_smile:

### CODE REVIEW

**Comment by Zir0h** [comment]
Also fix for https://github.com/teia-community/teia-ui/issues/288

**Comment by Zir0h** [comment]
Maybe at some point [URL.revokeObjectURL](https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL_static) still needs to be called to free the used memory from `URL.createObjectURL` ?

**Comment by melMass** [comment]
> Maybe at some point [URL.revokeObjectURL](https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL_static) still needs to be called to free the used memory from `URL.createObjectURL` ?

Yes I think too, otherwise it looks good, I would need to actually properly test it since all this is quite finicky

**Comment by Zir0h** [comment]
I think this could be merged too? I mean, it's already broken now, so it would be challenging to break it even harder :laughing:

**Comment by melMass** [comment]
True, and if it's breaking too much we can always revert it

**Review by melMass — APPROVED** [review]

**Comment by Zir0h** [comment]
> True, and if it's breaking too much we can always revert it

what could possibly go wrong, right? :rofl:

**Pull request merged**
