### PR TITLE
feat: Display OBJKTs that were flagged by the Teia content moderation team as NSFW or photosensitive.

### PR DESCRIPTION
**Pull request by Zir0h**
Very ugly fix for #373

### CODE REVIEW

**Comment by melMass** [comment]
This is d59703f98c0fa14e82a1b99859a62d7d4a12986c
image

**Comment by melMass** [comment]
**only show it for yourself** in cbf47b8fff3f990999d85b3de6d46f034b80547d

**moderation corner** (added in c00872e407b1e1e26471b7195151f798040ed055)
image

**Comment by melMass** [comment]
If we remove the BG style:
image

**Comment by Zir0h** [comment]
Nice! Looks way cleaner without the background I think!
Thanks for the help!

**Comment by Zir0h** [comment]
Maybe we also need to check when the objkt was minted, because the nsfw/photosensitive attributes didn't exist at the start

**Comment by melMass** [comment]
What do you mean? I mean how is this PR affecting that? I think we normalize it all and old mints can still be moderated

**Comment by Zir0h** [comment]
If I understood https://github.com/teia-community/teia-ui/issues/373 correctly, it's meant nudge repeat offenders of untagged nsfw/photo-sensitivity in the right direction.
It feels a bit unfair if you minted work really early and now you're seeing "you forgot to tag this, so we had to do it for you" all over your profile :sweat_smile:

**Comment by melMass** [comment]
I see what you mean now!
Not sure we should complexify it just for that tbh, but I'm open if it's a real issue

**Comment by Zir0h** [comment]
> I see what you mean now! Not sure we should complexify it just for that tbh, but I'm open if it's a real issue

Indeed, keep it simple :smile:

**Comment by melMass** [comment]
I think now that's it's a simple corner with text it's ok, with the stripped red borders maybe not 🤣

**Review by melMass — APPROVED** [review]

**Pull request merged**
