### PR TITLE
updated infra donation address

### PR DESCRIPTION
**Pull request by merchantcoppola**
new cold wallet for teis infra donations (held by manitcor)
added longform too bc enough space and people have been asking

### CODE REVIEW

**Comment by melMass** [comment]
Ah ok, I now understand, but this is just the display text, ktorn added it to the dropdown of the default suggested collaborators

**Comment by melMass** [comment]
image

**Comment by melMass** [comment]
image

**Review by melMass — APPROVED** [review]

**Comment by merchantcoppola** [comment]
mel now it says "please consider donating to the address" before the sentence starts again
or wait, actually in the code it looks fine .... i am confused.

**Comment by melMass** [comment]
> mel now it says "please consider donating to the address" before the sentence starts again or wait, actually in the code it looks fine .... i am confused.

I'm sorry I don't understand what you mean, I attached a screenshot of the result, you edited the wrong file, files in languages are only used in the about, but it's kept for future localization

**Comment by melMass** [comment]
Ah you're right my bad, IMO we should completely remove that sentence as it's already on the collab screen no?

**Comment by melMass** [comment]
Follow up in #100

**Pull request merged**
