### PR TITLE
feat: allow visitors to opt-out of the thumbnailing proxy

### PR DESCRIPTION
**Pull request by Zir0h**
I've seen some people dislike the imgproxy thumbnails, because "they are too centralized". With this pull request the visitors can choose to opt-out of using imgproxy and load full-size artifacts directly from ipfs.

### CODE REVIEW

**Comment by melMass** [comment]
Great!
Maybe this `click to disable imgproxy thumbnails and load fullsize images instead (performance penalty)` could specify `directly from IPFS` or something similar

**Comment by Zir0h** [comment]
I updated the message. I never see it tough :sweat_smile: chromium + firefox on linux, I hover over the checkbox and nothing pops up.

**Review by melMass — APPROVED** [review]

**Comment by melMass** [comment]
> I updated the message. I never see it tough 😅 chromium + firefox on linux, I hover over the checkbox and nothing pops up.

As you now know it's `title` 😄

**Comment by Zir0h** [comment]
> > I updated the message. I never see it tough 😅 chromium + firefox on linux, I hover over the checkbox and nothing pops up.
> 
> As you now know it's `title` 😄

thank you! :rofl: <3

**Review by melMass — APPROVED** [review]

**Review by melMass — APPROVED** [review]

**Pull request merged**
