### PR TITLE
fix: ⚡️ add the deployed commit in the readme

### PR DESCRIPTION
**Pull request by melMass**
This is a simple endpoint that parses the head on teia.art to fetch the deployed commit hash

### CODE REVIEW

**Comment by melMass** [comment]
https://github.com/teia-community/teia-ui/blob/13d5dab2cdbceecc6ff7b4832c6f86bd43bb0e6a/README.md

**Comment by LeonNicholls** [comment]
Is the code for https://melmassadian.npkn.net/teia-commit/ checked in somewhere?
Could this be hosted on a teia server somehow?

**Comment by melMass** [comment]
> 

I just made it public here: https://www.napkin.io/n/e66c793f570748a1
I will add the link to the merge commit ;)

**Comment by melMass** [comment]
> Could this be hosted on a teia server somehow?

I'm really unsure of what we can do technically on our servers, @jmagly might have a better approach

**Review by LeonNicholls — APPROVED** [review]

**Pull request merged**
