### PR TITLE
Teztok integration

### LINKED ISSUE #215: [feat] Switch to Teztok
### Describe the problem

I'm creating this issue to reference and close all the associated issues

### Describe the solution you'd like

Switch to Teztok

### Steps

- [ ] Display OBJKT.com swaps in the history
- [ ] Add support for Versum OBJKT swaps
- [ ] Display Tezos Domain instead of the address when available

### Additional context

Will address:
- #181 
- #210 
- #209 
	- **not sure about that one keeping it open for now, cc @xat)**

### PR DESCRIPTION
**Pull request by xat**
this is a work-in-progress pr of the teztok integration

### CODE REVIEW

**Comment by xat** [comment]
- [x] TODO: check why the subjkt data here is outdated => https://preview.teia.art/tz/tz2AHhNxa1EXvqi1z7uBbykvNtpt57MZhGnN?creations=80

**Comment by xat** [comment]
- [x] TODO: fix re-swap ui. see https://preview.teia.art/objkt/619598

**Comment by xat** [comment]
- [x] glb tokens are currently not displayed in the detail view

**Comment by xat** [comment]
@melMass it seems the glb doesn't show up on the detail-page because of this css change here: https://github.com/teia-community/teia-ui/pull/192/files#diff-37d7ac7ed85843273a64f3de70bdfe3321028f2ea5cc5a86470edda030c212fdR82

can you have a look at it?

**Comment by melMass** [comment]
> @melMass it seems the glb doesn't show up on the detail-page because of this css change here: [#192 (files)](https://github.com/teia-community/teia-ui/pull/192/files#diff-37d7ac7ed85843273a64f3de70bdfe3321028f2ea5cc5a86470edda030c212fdR82)
> 
> can you have a look at it?

The link doesn't redirect but I will look into it. I also wanted to fix 'controls' in feed view so you can rotate around without opening the detail view

**Comment by xat** [comment]
@melMass the problem is that the container is now "display: flex", which for some reason causes the glb to not get displayed.
Bildschirmfoto 2022-12-21 um 12 03 57

**Comment by xat** [comment]
- [x] check why the collaborators here are marked as unverified: https://preview.teia.art/objkt/799229

**Comment by xat** [comment]
- [x] on android & ios the tz-icon is not displayed correctly, replace with SVG provided by Den
- [x] it would be nice if the cursor would turn into a pointer when hovering buttons (grid-button, single-button, events-button, etc.)

**Comment by xat** [comment]
- [x] would be nice to have this on the same line
Bildschirmfoto 2023-01-24 um 09 06 31

**Comment by xat** [comment]
- [x] things are a bit stashed together here. maybe add some margin-top to the local settings and align the headline to the left?

Bildschirmfoto 2023-01-24 um 09 10 16

**Comment by xat** [comment]
it wasn't clear to me that these are two different buttons that do different things. from looking at it, i thought the rectangle on the left is for check-marking zen-mode.

Bildschirmfoto 2023-01-24 um 09 15 10

**Comment by xat** [comment]
- [x] maybe the tezos address could link to my own profile page?

Bildschirmfoto 2023-01-24 um 09 20 42

**Comment by xat** [comment]
- [x] fix router bug on profile page (i'll do this)

Bildschirmfoto 2023-01-24 um 09 22 51

**Comment by xat** [comment]
- [x] fix alignment of empty-view

Bildschirmfoto 2023-01-24 um 09 24 14

**Comment by melMass** [comment]
> it wasn't clear to me that these are two different buttons that do different things. from looking at it, i thought the rectangle on the left is for check-marking zen-mode.

Agreed, I personally don't like the UX of those buttons. I think I've solved the main design points to mentioned

**Comment by melMass** [comment]
- [ ] I did not look into it, but the url parms aren't doing anything `?recent-sales-feed=`

https://preview.teia.art/?recent-sales-feed=160

**Comment by merchantcoppola** [comment]
small thing:
- [x] dunno if intended, but in the "event" dropdown, i cant click anywhere to access the respective fundraiser feed.
if i click on the name of the event for example it doesnt take me to the event feed
nor is there a button or link to the feed it looks like
would also maybe be good to add tezospride there maybe

access feeds

**Comment by merchantcoppola** [comment]
- [x] another small thing that ONLY happens on my low-grade laptop:
the artworks on the vertical feed are skewed
using firefox 
feed stretched

**Comment by merchantcoppola** [comment]
one little feedback thingy: 
the disgner in my would really like to see some more space being given between the page and the footer, espoecially on the OBJKT pages its so close that its distracting imo
morespace

**Comment by merchantcoppola** [comment]
> > it wasn't clear to me that these are two different buttons that do different things. from looking at it, i thought the rectangle on the left is for check-marking zen-mode.
> 
> Agreed, I personally don't like the UX of those buttons. I think I've solved the main design points to mentioned

maybe for the dark modem, a moon symbol or even a rectangular shape thats more looking liuke a button could help?
switch

for zen mode id suggest to also just use a symbol so it appears hierachically the same (both buttons for different things)
when trhinking about it maybe it would be cool to take the zen symbol as an inspiration here (https://colorfullexperience.com/wp-content/uploads/2017/07/zen-symbol-4.png)

zen mode

**Comment by melMass** [comment]
> one little feedback thingy: the disgner in my would really like to see some more space being given between the page and the footer, espoecially on the OBJKT pages its so close that its distracting imo morespace

Yep I asked @denscimonk about that he is looking into the best approach

> maybe for the dark modem, a moon symbol or even a rectangular shape thats more looking liuke a button could help?

I think that's also a question for Den

**Comment by scalemodal** [comment]
Menu on desktop:
- [x] Icons 16x16
- [x] Font "Events" 16px
- [x] "Collaborate" to right part of menu
- [ ] More space between dark/light/zen buttons, and menu items
- [ ] Longer line divider
- [ ] Same line alignment (Events, divider...)
- [x] Removing second logo from footer in menu
- [ ] "This open-source, experimental dApp...." and "Teia DAO LLC" texts TBD
- [x] Removing "Friends" from menu (if we can add it to the feed select)
- [ ] Considering to add pages "Events", "Search", "Gallery"

image

**Comment by scalemodal** [comment]
Homepage on desktop, masonry view.

- [ ] ~~Missing hover OBJKT card~~ (log into a dedicated issue)
- [x] Better vertical/masonry icons export (masonry one is broken)
- [ ] Deciding about search feature. I would bring it back (removing divider from homepage in that case, because search input field will work as the divider visually)

image

**Comment by scalemodal** [comment]
Desktop footer

- [x] Missing main footer divider (line between footer and content on top)
- [ ] Missing vertical divider on menu
- [ ] Better menu items alignment
- [ ] More space between logo and "Teia DAO LLC"
- [ ] Same dark/light/zen buttons size
- [ ] Would add "Code and Conduct" and "Terms and Conditions" links after info
- [ ] Same line alignment (global thing in many places)

image

**Comment by scalemodal** [comment]
Feed select on desktop

- [x] Missing chevron icon
- [x] Better menu items alignments (see design near on the right side)
- [x] Grouping menu items as:
1. Feed type (recent, random, new, friends)
2. Events
3. Files type (image, video...)

- [ ] Friends is inactive when when unsynced TBD


image

**Comment by scalemodal** [comment]
Big OBJKT card on vertical mode feed, desktop:

- [ ] Design with frame/border, different alignment and spacing (see pic on the right side)
- [ ] Missing OBJKT number
- [ ] All fonts 16px on big cards

image

**Comment by scalemodal** [comment]
**OBJKT / Info page**

Desktop: https://www.figma.com/file/R5sw1HcoHx4Aup1Yl7rGYA/UX%2FUI-Development?node-id=3417%3A2107&t=539oDcRjZtq40dm5-1

Mobile: https://www.figma.com/file/R5sw1HcoHx4Aup1Yl7rGYA/UX%2FUI-Development?node-id=3417%3A2423&t=539oDcRjZtq40dm5-1


image

--------

**Comment by scalemodal** [comment]
"Assets" page design for comparison with implemented version:

Desktop: https://www.figma.com/file/R5sw1HcoHx4Aup1Yl7rGYA/UX%2FUI-Development?node-id=3417%3A2661&t=539oDcRjZtq40dm5-1

Mobile: https://www.figma.com/file/R5sw1HcoHx4Aup1Yl7rGYA/UX%2FUI-Development?node-id=3417%3A3018&t=539oDcRjZtq40dm5-1

image

**Comment by melMass** [comment]
Thanks @denscimonk for the bullet, I was overwhelmed by the discord messages, but these are clearer.
Most points are valid but:
- I need the logos, I roughly did it from the figma 
- "More space" needs to be defined, that's kind of the point I was trying to make 2 month ago that we need all the "needs" to come up with the best implementation.
- The "Hover" card, I will look into it but consider it the lowest priority on the list given it was added late to the design.

I will address the rest this week

**Comment by scalemodal** [comment]
@melMass Exported new icons:
[teia-icons-jan2023.zip](https://github.com/teia-community/teia-ui/files/10501916/teia-icons-jan2023.zip)

Pls replace all icons with the newly exported ones. First try masonry and vertical feed icons, if it works without glitches.

**Comment by scalemodal** [comment]
@melMass Let's try exact margins and font specs on artboards, let me know, if it will help you.
You can always see fonts specs on Figma under Inspect tab in right sidebar. I would not always specify fonts like that, as you see on the pic now, but we can do it with margins, because these are not obvious from Figma.

- [x] OBJKT / Info (Desktop)
image

**Comment by LeonNicholls** [comment]
- [x] Oops. Created this bug before I found out about this thread: https://github.com/teia-community/teia-ui/issues/243

**Comment by LeonNicholls** [comment]
https://preview.teia.art/mint
- [x] Clicking on the NSFW or Photosensitive checkboxes does not work.

**Comment by melMass** [comment]
Yep, tbh this is not the best time for feedback as the last few commits broke a few things for instance on mobile! I will pick it up tomorrrow

**Comment by melMass** [comment]
- [x] Can't swap ~~from collab~~ (at all actually, not only collabs)
image

**Comment by melMass** [comment]
I migrated all the remaining bullet points logged here on discord.
Please don't use this PR commenting space for feedbacks. If you can't go to the discord "Beta Feedback" main channel, open a new issue and I will tag it with beta.

Thanks

**Pull request merged**
