### PR TITLE
update taquito

### LINKED ISSUE #397: [feat] update beacon
### Describe the problem

@Zir0h @Surfingthedarkness who should i reach out to on the Teia discord or elsewhere to get devs to update the teia.art apps version of beacon, its on a really old version that we can't test against Kukai iOS. Ideally they update to the latest version 4.2.0 that was released this Monday https://github.com/airgap-it/beacon-sdk/releases/tag/v4.2.0 but even one from a month ago is better than the one that is currently in use.

- cousinit on the mooncakes discord

### Describe the solution you'd like

update beacon

### Alternatives considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Zir0h**
fixes #397

### CODE REVIEW

**Comment by melMass** [comment]
Finally!
Very nice.
Did you test it?

**Comment by Zir0h** [comment]
> Finally! Very nice. Did you test it?

yes, but only basic stuff, sync/unsync collect, I'll check more later this afternoon

**Comment by Zir0h** [comment]
ehh, wait, it doesn't look like this is the release the kukai team wants to have :sweat_smile: 

2024-05-04-113115_2013x227_scrot

**Comment by Zir0h** [comment]
https://github.com/ecadlabs/taquito/commit/4360f9c0758efe74c6d0263ce277321e54a2efab still needs to be adapted in the teia code

**Comment by melMass** [comment]
> when a wallet would disconnect the teia app wouldn't know how to deal with it

Is it a known issue I'm not aware of? 😅

---

I think adapting shouldn't be too hard but I just wonder if we shouldn't wait for after beta? Or is it urgent to update for another reason?

Cc @cousinit

**Comment by Zir0h** [comment]
> > when a wallet would disconnect the teia app wouldn't know how to deal with it
> 
> Is it a known issue I'm not aware of? 😅
> 
> I think adapting shouldn't be too hard but I just wonder if we shouldn't wait for after beta? Or is it urgent to update for another reason?
> 
> Cc @CousinIt

no, I don't think there's an immediate issue

yeah, I'd like to wait for a full release too, that's why I also marked this PR as a draft for now

**Comment by Zir0h** [comment]
The `BeaconEvent` stuff does seem to be causing some issues, but I don't know if we really need that :thinking: 

```
✘ [ERROR] Could not read from file: /home/user/teia-ui/vite-compatible-readable-stream

    ../node_modules/cipher-base/index.js:2:24:
      2 │ var Transform = require('stream').Transform
        ╵                         ~~~~~~~~

8:18:01 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
../node_modules/cipher-base/index.js:2:24: ERROR: Could not read from file: /home/user/teia-ui/vite-compatible-readable-stream
    at failureErrorWithLog (/home/user/teia-ui/node_modules/esbuild/lib/main.js:1649:15)
    at /home/user/teia-ui/node_modules/esbuild/lib/main.js:1058:25
    at /home/user/teia-ui/node_modules/esbuild/lib/main.js:1525:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Zir0h** [comment]
I pushed this to https://preview.teia.art/

**Comment by Zir0h** [comment]
I updated everything except react-pdf and eslint, because they gave errors and I'm not smart enough to fix them :sweat_smile:

**Comment by Zir0h** [comment]
Sometimes it works, sometimes it does not (with walletconnect wallets)
2024-05-08-202252_1200x293_scrot

**Comment by Zir0h** [comment]
The error is related to the static build, using the node dev webserver gives no issues :/

**Comment by Zir0h** [comment]
```
Uncaught (in promise) TypeError: "list" argument must be an Array of Buffers
    concat contracts-B2xcCTA_.js:11
    JC crypto.js:166
    onNewAccount DAppClient.js:1775
    requestPermissions DAppClient.js:1013
    requestPermissions taquito-beacon-wallet.es6.js:91
    fs taquito-beacon-wallet.es6.js:30
    fs taquito-beacon-wallet.es6.js:26
    requestPermissions taquito-beacon-wallet.es6.js:90
    sync userStore.ts:203
    $ Header.jsx:148
    React 16
 ```

**Comment by Zir0h** [comment]
feedback from the kukai devs:
image

**Comment by Zir0h** [comment]
So I'm guessing we're running into the "˚ shimmed, but too complex to polyfill fully. Avoid if at all possible. Some bugs and partial support expected." disclaimer from https://www.npmjs.com/package/rollup-plugin-polyfill-node :rofl: 

so, this update is probably a no-go

**Comment by melMass** [comment]
> so, this update is probably a no-go

Yep I think too unless there is a real reason to. Once it's "stable" or not beta we can try again, I'm just hoping they are now properly bundling it so we can remove 3/4th of our vite config (all this should be done upstream https://github.com/ecadlabs/taquito/issues/1281#issuecomment-1095572781)

**Comment by Zir0h** [comment]
https://github.com/ecadlabs/taquito/releases/tag/20.0.2-beta.2 looks like all the messing around that I did in this PR won't be necessary. I think it's better to create a new PR (when taquito gets out of beta) and trash this one?

**Comment by melMass** [comment]
Yeah 😅 
I'm also willing to help of cleaning up our vite config since I introduced a bunch of hacks we might not need anymore

**Comment by Zir0h** [comment]
Will try again later (probably)

**Pull request closed without merging**
