### PR TITLE
fix: avoid out of memory when minting large files

### PR DESCRIPTION
**Pull request by Zir0h**
I tried to fix the out of memory bug from #280 with the suggestion @melMass posted. I don't know if I implemented it correctly tough. It seems to work as expected.

### CODE REVIEW

**Comment by melMass** [comment]
You are on fire ❤️!
I just missed my train so I'll have a look a bit later today

**Comment by melMass** [comment]
I'm getting 

`Uncaught (in promise) DOMException: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.`

For a 5Gb file.

As I'm looking into it it seems that chrome for instance has an ArrayBuffer size limit of 2GB... So we need to chunk it somehow 😓

**Comment by Zir0h** [comment]
> I'm getting
> 
> `Uncaught (in promise) DOMException: The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.`
> 
> For a 5Gb file.
> 
> As I'm looking into it it seems that chrome for instance has an ArrayBuffer size limit of 2GB... So we need to chunk it somehow 😓

Good thing we limited minting to 2GB :rofl:

**Comment by melMass** [comment]
Oops! But with a 1.5GB I get this without errors in the console though

image

**Comment by melMass** [comment]
Ohhh ok there was just a delay between the time it catched the first one to then display the cover... For large file there should probably be some kind of loader to indicate that

**Comment by melMass** [comment]
In any case not related to this PR, it works!
But we should improve the mint UX a bit imo

**Comment by Zir0h** [comment]
> But we should improve the mint UX a bit imo

I agree 100%! But I'm not good with frontend stuff :laughing:

**Review by melMass — APPROVED** [review]
Perfect!

In a next PR we should probably:
- check the size of the file and alert about that
- Add some kind of load state after selecting the main mint file, as the UI Isn't blocked one can click submit which fails the validation, not a big deal since once loaded the button for the cover appears and the mint state is restored

**Pull request merged**
