### PR TITLE
Make collab names/addresses clickable

### LINKED ISSUE #19: [feat] make collab username clickable
on the signing status modal, it would be great if the usernames were clickable to go to that profile directly... would likely reduce confusion and risk of scams

(submittet by aebrer on discourse)

collabclick

### LINKED ISSUE #31: [feat] signing summary missing, since update
looks like the inline dialog that shows a list of signers got lost due to the update. we should re-add it.

this here is currently missing:
Bildschirmfoto 2022-03-20 um 13 28 13

### PR DESCRIPTION
**Pull request by melMass**
* fix: ✨ fixes #19, prevent event bubbling

This is half a solution to the problem of preventing event bubbling.

### CODE REVIEW

**Review by aebrer — APPROVED** [review]
looks great to me! 😄

**Comment by aebrer** [comment]
only potential issue is the verification checkmarks don't seem to be showing, but that's true on the prod site anyway, so I'm not sure it's related to this directly

**Comment by melMass** [comment]
> only potential issue is the verification checkmarks don't seem to be showing, but that's true on the prod site anyway, so I'm not sure it's related to this directly

It is indeed coming from before... But it's a good candidate to also fix in this PR.
I will look at xat's fix in roughly an hour and compare it with before we merged the UI WG PRs!

**Comment by xat** [comment]
looks good to me. what do you think @melMass ?

**Comment by xat** [comment]
@aebrer if you think it's fine, can you approve the PR? you are set as reviewer who needs to approve, before we can merge :)

**Review by aebrer — APPROVED** [review]
looks good to me :)

**Comment by aebrer** [comment]
@xat I'm not sure my review counts though, it still says it needs an approved review

**Review by xat — APPROVED** [review]

**Comment by xat** [comment]
@aebrer ah true, apparently i also needed to approve, even though i wasn't set as a reviewer :-)

@melMass if there is nothing left from your side, i think it can be merged.

**Comment by melMass** [comment]
> @melMass if there is nothing left from your side, i think it can be merged.

Good to go for now for me!
It will need refactoring once we are there

**Pull request merged**
