### PR TITLE
dipdup5 support

### PR DESCRIPTION
**Pull request by xat**
work-in-progress

### CODE REVIEW

**Comment by Zir0h** [comment]
If I click on the Ukraine link, the screen stays empty and the following message appears in the web dev console:
`{"errors":[{"extensions":{"path":"$.selectionSet.splitcontract","code":"validation-failed"},"message":"field \"splitcontract\" not found in type: 'query_root'"}]}`
There's a field `split_contract`, but not `splitcontract` in hasura.

**Comment by melMass** [comment]
What is the status of all this ? :)

**Comment by xat** [comment]
fixed the splitcontract-problem.

**Comment by xat** [comment]
this was tested by a couple of people (also as part of pr 85). major issues were fixed, so i'll merge it now.

**Pull request merged**
