### PR TITLE
Switch the default rpc node to mainnet.teia.rocks

### PR DESCRIPTION
**Pull request by Zir0h**
mainnet.api.tez.ie has been down for a couple of hours already, people are going to start to notice pretty soon :sweat_smile:

### CODE REVIEW

**Comment by melMass** [comment]
Tchoop tchoop! 
What is the reasoning for moving the keys around? If it's to "force" reset user config we can just use versioning on the config

**Comment by Zir0h** [comment]
> Tchoop tchoop! What is the reasoning for moving the keys around? If it's to "force" reset user config we can just use versioning on the config

No I thought the order was the same as the array, I didn't find the `  rpcNode: rpc_nodes[0],` until after the third try :sweat_smile:

**Comment by melMass** [comment]
My bad I looked at the commits not the final diff so I was confused.

**Review by melMass — APPROVED** [review]
Rocks!

**Comment by Zir0h** [comment]
> My bad I looked at the commits not the final diff so I was confused.

yeah sorry, I was fumbling around a bit :laughing: 
anyway, it looks like the original node is fixed now https://mainnet.api.tez.ie/chains/main/blocks/head/header but I think switching would still be a good idea
that node hasn't been very stable

**Pull request merged**
