### PR TITLE
fix: ⚡️ merge n lists (both allow and restrict)

### PR DESCRIPTION
**Pull request by melMass**
Removes HEN list fetching

### CODE REVIEW

**Comment by xat** [comment]
currently, both, the restricted-list and the permitted-list, are coming from the teia repo. does it make sense to keep these lists separated? because otherwise, this could be one single list with only the restricted accounts. the permitted accounts could just be removed from the restricted-list (since we are in control of that list).

**Comment by LeonNicholls** [comment]
The separate permitted list does give us the option of overriding other lists that we might combine with the teia list for all the restrictions.

**Comment by melMass** [comment]
> currently, both, the restricted-list and the permitted-list, are coming from the teia repo. does it make sense to keep these lists separated? because otherwise, this could be one single list with only the restricted accounts. the permitted accounts could just be removed from the restricted-list (since we are in control of that list).

Imo it's more modular, if we want to optin others list for instance.

**Comment by xat** [comment]
makes sense 👍

**Review by xat — APPROVED** [review]
👍

**Pull request merged**
