### PR TITLE
Minting metadata improvements 

### PR DESCRIPTION
**Pull request by LeonNicholls**
Based on https://docs.google.com/document/d/1R3rxuJfpCBoh52wDsYpEmY_iuH8sd6l17oh4nk7jlRE/edit?usp=sharing

New fields still need to be added to the GUI.

### CODE REVIEW

**Comment by melMass** [comment]
Very nice!

**Comment by melMass** [comment]
Just listing the needs @NoRulesJustFeels :

- `rights` -> predefined dropdown?
- `rightUri` -> A url to the license (predefined dropdown?) 
- `language` -> predefined flags dropdown for each lang (https://www.loc.gov/standards/iso639-2/php/code_list.php)
- `attributes` -> key,value widget/sanitized
- `formats` -> not too sure there is any control for that right? (like compression)
- `NSFW` -> checkbox
- `photosensitiveSeizureWarning` -> checkbox

**Comment by LeonNicholls** [comment]
For rights, it would be similar to versum where they have a "Licence type" dropdown for several standard licences:
No License
Creative Commons Zero v1.0 Universal
Creative Commons Attribution 4.0 International
Attribution-ShareAlike 4.0 International
Custom License

If you select a "Custom License" a textarea appears where you can type in text; for Teia it would be the URL for the license and would be stored in rigthUri.

Language is fine to have the dropdown for each lang.

Attributes would not be exposed as a data structure in the GUI (other than the 2 flags below).
Formats would not be exposed as a data structure in the GUI.

NSFW should be a checkbox.
photosensitiveSeizureWarning should be a checkbox.

**Comment by melMass** [comment]
Hey,

This is going to be my last contribution for teia.
I'll tackle it today.

Cheers

**Comment by melMass** [comment]
Picked up in #113

**Pull request closed without merging**
