### PR TITLE
feat: copy/pasta from the previous quake aid fundraiser

### PR DESCRIPTION
**Pull request by Zir0h**

### CODE REVIEW

**Comment by Zir0h** [comment]
This enables the feed for the new contract address `KT1RwXEP8Sj1UQDHPG4oEjRohBdzG2R7FCpA`

**Comment by merchantcoppola** [comment]
i changed the text a little bit but other than that it shoudl be fine no?
i didnt see where it checks trhe donation address for morocco tho

**Comment by Zir0h** [comment]
> i changed the text a little bit but other than that it shoudl be fine no? i didnt see where it checks trhe donation address for morocco tho

it gets filled in with this variable: [${contractAddress}](https://github.com/teia-community/teia-ui/blob/bd0692e76e0f98db7e42a261a096988b9d5829a0/src/pages/home/feeds/fund-feed.jsx#L70 )

**Comment by melMass** [comment]
@Zir0h Just so you know if you create branches on teia-community/teia-ui directly it would make staging deploys

**Review by merchantcoppola — APPROVED** [review]
tried my best to check, to me it looks good to go

**Comment by Zir0h** [comment]
> @Zir0h Just so you know if you create branches on teia-community/teia-ui directly it would make staging deploys

woops, force of habit, thanks!

**Pull request merged**
