### PR TITLE
adding a troubleshooting section

### PR DESCRIPTION
**Pull request by merchantcoppola**
i notoced a lot of similar issues mentioned on discord, maybe we should give the most common solutions directly on the page?

### CODE REVIEW

**Comment by Zir0h** [comment]
very smart!

**Comment by merchantcoppola** [comment]
not too sure about the whole syntax thing, esp with the list, the headline formatting and the links ... maybe someone can have a look and check if i guesstimated it correctly

the preview doesnt show the section, maybe i messed smth up?

**Comment by Zir0h** [comment]
> not too sure about the whole syntax thing, esp with the list, the headline formatting and the links ... maybe someone can have a look and check if i guesstimated it correctly
> 
> the preview doesnt show the section, maybe i messed smth up?

the github preview looks good to me
2023-08-21-095554_1867x723_scrot

**Comment by melMass** [comment]
Nice!
We just need to apply hooks please (or even prettier on its own), I forgot to do it for yesterday's merge and it created a big mess in my branches 😅!
I will check if there is a way to apply them when using GitHub UI to edit the files

**Review by melMass — APPROVED** [review]
Great idea!

**Pull request merged**
